package com.efinancialcareers.enums;

public enum Sector {

    ACCOUNTING_FINANCE(1),
    ASSET_MANAGEMENT(2),
    CAPITAL_MARKETS(3),
    COMMODITIES(4),
    COMPLIANCE_LEGAL(5),
    CONSULTANCY(6),
    CORPORATE_BANKING(7),
    CREDIT(8),
    DEBT_FIXED_INCOME(9),
    DERIVATIVES(10),
    EQUITIES(11),
    FX_MONEY_MARKETS(12),
    GLOBAL_CUSTODY(13),
    GRADUATES_INTERNSHIPS(14),
    HEDGE_FUNDS(15),
    HR_RECRUITMENT(16),
    INDUSTRY_COMMERCE(17),
    INFORMATION_SERVICES(18),
    INFORMATION_TECHNOLOGY(19),
    INSURANCE(20),
    INVESTMENT_BANKING_M_A(21),
    INVESTMENT_CONSULTING(22),
    INVESTOR_RELATIONS_PR(23),
    ISLAMIC_FINANCE(24),
    OPERATIONS(25),
    PRIVATE_BANKING_WEALTH_MANAGEMENT(26),
    PRIVATE_EQUITY_VENTURE_CAPITAL(27),
    PUBLIC_SECTOR(28),
    QUANTITATIVE_ANALYTICS(29),
    REAL_ESTATE(30),
    RESEARCH(31),
    RETAIL_BANKING(32),
    RISK_MANAGEMENT(33),
    SALES_MARKETING(34),
    TRADING(35);

    private Integer id;

    private Sector(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }
}
